#
# Module shared libraries and variables
#

#
# Globals
#

# shellcheck disable=SC2034
{
  # SysDen64 / Common messages
  readonly SYSDEN64_TXT_NOT_DETECTED='tool not detected. No further action taken'
  readonly SYSDEN64_TXT_WATERMARK='# Warning: configuration file generated by SysDen64. DO NOT MODIFY'
  readonly SYSDEN64_MODULE_TYPE_SHARED='S'
  readonly SYSDEN64_MODULE_TYPE_DEDICATED='D'
}

#
# Functions
#

function module_config_backup() {
  bl64_dbg_app_show_function "$@"
  local model="$1"
  local target=''
  local source=''
  shift
  bl64_check_parameter 'model' || return $?

  target="${SYSDEN64_PATH_BACKUP}/${model}"
  if [[ ! -d "$target" ]]; then
    bl64_msg_show_task "create configuration backup repository (${SYSDEN64_PATH_BACKUP})"
    bl64_fs_dir_create \
      "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" \
      "$SYSDEN64_PATH_BACKUP" \
      "$target" ||
      return $?
  else
    bl64_dbg_app_show_info 'detected previous sysden64 run, no cfg backups will be taken'
    return 0
  fi

  for source in "$@"; do
    if [[ -f "$source" || -d "$source" ]]; then
      bl64_msg_show_task "backup previous configuration files (${source} -> ${SYSDEN64_PATH_BACKUP})"
      bl64_fs_run_mv \
        "$BL64_FS_SET_MV_FORCE" \
        "$source" \
        "$target" ||
        return $?
    fi
  done
}

function module_check_type() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  if [[ "$module_type" != "$SYSDEN64_MODULE_TYPE_DEDICATED" &&
    "$module_type" != "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
    bl64_msg_show_error "invalid module type (${module_type})"
    return $BL64_LIB_ERROR_PARAMETER_INVALID
  fi
}

function module_create_shared() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  local module="$2"

  bl64_check_parameter 'model' &&
    module_check_type "$module_type" ||
    return $?
  if ! bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USER_WIDE"; then
    bl64_dbg_app_show_info 'user-wide is disabled. No further action taken'
    return 0
  fi

  if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
    bl64_dbg_app_show_info 'shared configuration is disabled for the module. No further action taken'
    return 0
  fi

  if [[ ! -d "${SYSDEN64_PATH_SHARED}/${module}" ]]; then
    bl64_msg_show_task "create shared user-wide configuration model (${SYSDEN64_PATH_SHARED}/${model})"
    bl64_fs_path_copy \
      "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" \
      "$SYSDEN64_PATH_SHARED" \
      "${SYSDEN64_PATH_ETC}/${module}" ||
      return $?
  fi
}

function module_set_model() {
  local module_type="$1"
  local module="$2"
  module_check_type "$module_type" ||
    return $?
  if bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USER_WIDE"; then
    if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
      echo "$SYSDEN64_PATH_ETC/$module"
    elif [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
      echo "${SYSDEN64_PATH_SHARED}/${module}"
    fi
  else
    echo "$SYSDEN64_PATH_ETC/$module"
  fi
}

function module_sync_allow() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  module_check_type "$module_type" ||
    exit $?
  if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
    bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_MODULE_SYNC"
  elif [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
    bl64_dbg_app_show_info 'shared module. Always allow sync'
    return 1
  fi
}

function module_profile_switch_allow() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  module_check_type "$module_type" ||
    exit $?
  if bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USER_WIDE"; then
    if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
      bl64_dbg_app_show_info 'not a shared module. Always switch profile'
      return 1
    elif [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
      bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_PROFILE_SWITCH"
    fi
  else
    bl64_dbg_app_show_info 'user-wide is disabled. Ignore profile switch'
    return 1
  fi
}
