#
# Module shared libraries and variables
#

#
# Globals
#

# shellcheck disable=SC2034
{
  # SysDen64 / Common messages
  readonly SYSDEN64_TXT_NOT_DETECTED='tool not detected. No further action taken'
  readonly SYSDEN64_TXT_CONFIGURED='already configured. No further action taken'
  readonly SYSDEN64_TXT_WATERMARK='# Warning: configuration file generated by SysDen64. DO NOT MODIFY'
  readonly SYSDEN64_MODULE_TYPE_SHARED='S'
  readonly SYSDEN64_MODULE_TYPE_DEDICATED='D'
}

#
# Functions
#

function module_check_type() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  if [[ "$module_type" != "$SYSDEN64_MODULE_TYPE_DEDICATED" &&
    "$module_type" != "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
    bl64_msg_show_error "invalid module type (${module_type})"
    # shellcheck disable=SC2086
    exit $BL64_LIB_ERROR_PARAMETER_INVALID
  fi
}

function module_create_shared() {
  bl64_dbg_app_show_function "$@"
  local module="$1"
  local module_type="$2"

  module_check_type "$module_type"
  if ! bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USE_DEVBIN64"; then
    bl64_dbg_app_show_info 'user-wide is disabled. No further action taken'
    return 0
  fi

  if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
    bl64_dbg_app_show_info 'shared configuration is disabled for the module. No further action taken'
    return 0
  fi

  if [[ ! -d "${SYSDEN64_PATH_SHARED}/${module}" ]]; then
    bl64_msg_show_task "create shared user-wide configuration model (${SYSDEN64_PATH_SHARED}/${model})"
    bl64_fs_path_copy \
      "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" "$BL64_VAR_DEFAULT" \
      "$SYSDEN64_PATH_SHARED" \
      "${SYSDEN64_PATH_ETC}/${module}" ||
      return $?
  fi
}

function module_set_model() {
  local module="$1"
  if bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USE_DEVBIN64"; then
    echo "${SYSDEN64_PATH_SHARED}/${module}"
  else
    echo "$SYSDEN64_PATH_ETC/$module"
  fi
}

function module_sync_allow() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  module_check_type "$module_type"
  if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
    bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_MODULE_SYNC"
  elif [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
    bl64_dbg_app_show_info 'shared module. Always allow sync'
    return 1
  fi
}

function module_profile_switch_allow() {
  bl64_dbg_app_show_function "$@"
  local module_type="$1"
  module_check_type "$module_type"
  if bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_USE_DEVBIN64"; then
    if [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_DEDICATED" ]]; then
      bl64_dbg_app_show_info 'not a shared module. Always switch profile'
      return 1
    elif [[ "$module_type" == "$SYSDEN64_MODULE_TYPE_SHARED" ]]; then
      bl64_lib_flag_is_enabled "$SYSDEN64_FLAG_PROFILE_SWITCH"
    fi
  else
    bl64_dbg_app_show_info 'user-wide is disabled. Ignore profile switch'
    return 1
  fi
}
