# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.0.0

# Allow local binaries to be executed
fish_add_path /usr/local/bin
