# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.1.0

#
# Normalize the TMP and TMPDIR environment variables
#

set -gx  TMP '/tmp'
set -gx  TMPDIR "$TMP"

#
# Normalize terminal type
#

if test -z "$TERM"
    set -gx  TERM "xterm-256color"
end
