# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 3.0.0

# Load .env files
if [[ -d "${HOME}/.env.d" ]]; then
  _module=""
  for _module in "${HOME}/.env.d"/*.env ; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi
