# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 2.0.0

# ZSH
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="false"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"
