# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 1.0.0

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ZSH
CASE_SENSITIVE="false"
HYPHEN_INSENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UPDATE_PROMPT="false"
ENABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"
ZSH_THEME="powerlevel10k/powerlevel10k"

#
# OhMyZSH plugins
#

plugins=(
ansible
argocd
aws
azure
colored-man-pages
colorize
command-not-found
common-aliases
debian
dnf
dnf
docker
fluxcd
gcloud
gh
git
git-prompt
helm
istioctl
kind
kubectl
minikube
pip
python
ssh
systemd
terraform
ubuntu
vi-mode
virtualenv
yum
fzf-tab
zsh-completions
zsh-syntax-highlighting
zsh-autosuggestions
zsh-interactive-cd
)

# SysDen64
[[ -d '/sa/bin/' ]] &&
  cd '/sa' &&
  source '/sa/bin/dev-set-sysden64'

# OhMyZSH
export ZSH="${HOME}/.oh-my-zsh"
source "${ZSH}/oh-my-zsh.sh"

# PowerLevel10K
source "${HOME}/.p10k.zsh"
