#!/usr/bin/env bash

if [[ "$DEV_TEST_BASH_CONTAINER_ENVIRONMENT" != 'ON' ]]; then
  echo 'error: Test must be executed inside a container'
  exit 1
fi

source ./test/lib/test.env &&
./src/bin/sysden64 -s -i $HOME/test -p profile1 &&
./src/bin/sysden64 -w -i $HOME/test -p profile2 &&
./src/bin/sysden64 -w -i $HOME/test -p profile3
