
# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 1.0.0

# Load .env files
if test -d "$HOME/.env.d"
  # Load shell settings and functions
  for _module in "$HOME"/.env.d/*.fish
    if test -r "$_module"
        source "$_module"
    end
  end
end
