
# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.0.0

# Load .env files
if test -d "$HOME/.env.d"
  # Load shell settings and functions
  for _module in "$HOME"/.env.d/*.fish
    if test -r "$_module"
        source "$_module"
    end
  end
end
