# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 1.0.0

#
# Fix path_helper order
#

# First reset previous path
PATH=''

# Generate MacOS default path
eval "$(/usr/libexec/path_helper -s)"

# Add SysDen64 generated paths
PATH="${PATH_SYSDEN64}:${PATH}"

export PATH
