# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.2.0

# Enable OMZ plugins
plugins=(
  aws
  azure
  colored-man-pages
  colorize
  command-not-found
  common-aliases
  docker
  gcloud
  gh
  git
  git-prompt
  helm
  istioctl
  kind
  kubectl
  minikube
  pip
  python
  ssh
  terraform
  virtualenv
  fzf-tab
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  zsh-interactive-cd
)

zstyle ':omz:update' mode disabled
# Load OMZ
source "${ZSH}/oh-my-zsh.sh"
