# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 2.0.0

# Enable OMZ plugins
# * zsh-syntax-highlighting: must be last in the list
plugins=(
  colored-man-pages
  command-not-found
  git-prompt
  ssh
  terraform
  virtualenv
  fzf-tab
  zsh-autosuggestions
  zsh-interactive-cd
  zsh-syntax-highlighting
)

# Optional plugins
#  ansible
#  argocd
#  aws
#  azure
#  colorize
#  common-aliases
#  debian
#  dnf
#  docker
#  fluxcd
#  gcloud
#  gh
#  git
#  helm
#  istioctl
#  kind
#  kubectl
#  minikube
#  pip
#  python
#  systemd
#  ubuntu
#  vi-mode
#  yum

# ZSH-Completions / Initialize
# * Must load before OMZ
if [[ -r "${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src" ]]; then
  fpath+="${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src"
  autoload -U compinit && compinit
fi

# OMZ / Initialize
zstyle ':omz:update' mode disabled
source "${ZSH}/oh-my-zsh.sh"
