# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 3.0.0

#
# Add XDG directories to the PATH
#

# Local bin
fish_add_path "$HOME/bin"

# XDG
fish_add_path "$HOME/.local/bin"
