# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u
# Version: 1.1.0

# Set initial system path
export PATH="/bin:/usr/bin"

# Load global RC
[[ -f /etc/bashrc ]] &&
  source /etc/bashrc

# Load user RC
if [[ -d "${HOME}/.bashrc.d" ]]; then
  _module=""
  for _module in "${HOME}/.bashrc.d"/*.sh; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi

# Load .env files
if [[ -d "${HOME}/.env.d" ]]; then
  _module=""
  # Load variables, paths and aliases
  for _module in "${HOME}/.env.d"/*.env ; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  # Load shell settings and functions
  for _module in "${HOME}/.env.d"/*.bash ; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi
