#!/usr/bin/env bash
# Warning: configuration file generated by SysDen64. DO NOT MODIFY

# Set initial system path
export PATH="/bin:/usr/bin"

# Load global RC
[[ -f /etc/bashrc ]] &&
  source /etc/bashrc

# Load user RC
if [[ -d "${HOME}/.bashrc.d" ]]; then
  _module=""
  for _module in "${HOME}/.bashrc.d"/*.sh; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi

# Load .env files from user store
if [[ -d "${HOME}/.env.d" ]]; then
  _module=""
  for _module in "${HOME}/.env.d"/*.env; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi
