# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 2.0.0

export PATH="/bin:/usr/bin:/usr/local/bin:${HOME}/.local/bin:${HOME}/bin"

[[ -f '/etc/bashrc' ]] &&
  source '/etc/bashrc'

if [[ -d "${HOME}/.bashrc.d" ]]; then
  _module=""
  for _module in "${HOME}/.bashrc.d"/*.sh; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi

# Load .env files
if [[ -d "${HOME}/.env.d" ]]; then
  _module=""
  for _module in "${HOME}/.env.d"/*.env; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi
