# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 2.0.0

# Load Powerlevel10k configuration
source "${HOME}/.p10k.zsh"
