# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.0.0

if test -d "$HOME/Library/Python/3.9/bin"
  fish_add_path "$HOME/Library/Python/3.9/bin"
else if test -d "$HOME/Library/Python/3.8/bin"
  fish_add_path "$HOME/Library/Python/3.8/bin"
end
