# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 1.1.0

# Enable OMZ plugins
plugins=(
  ansible
  argocd
  aws
  azure
  colored-man-pages
  colorize
  command-not-found
  common-aliases
  debian
  dnf
  dnf
  docker
  fluxcd
  gcloud
  gh
  git
  git-prompt
  helm
  istioctl
  kind
  kubectl
  minikube
  pip
  python
  ssh
  systemd
  terraform
  ubuntu
  vi-mode
  virtualenv
  yum
  fzf-tab
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  zsh-interactive-cd
)

zstyle ':omz:update' mode disabled
# Load OMZ
source "${ZSH}/oh-my-zsh.sh"
