# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u
# Version: 3.1.0

# Load .env files
if [[ -d "${HOME}/.env.d" ]]; then
  _module=""
  # Load variables, paths and aliases
  for _module in "${HOME}/.env.d"/*.env ; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  # Load shell settings and functions
  for _module in "${HOME}/.env.d"/*.zsh ; do
    [[ -r "$_module" ]] &&
      source "$_module"
  done
  unset _module
fi
