# Warning: configuration file generated by SysDen64. DO NOT MODIFY
# Version: 1.0.0

#
# Custom shell definition
#
# * Use to add custom functions and configuration settings to the shell
# * Shell specific code is allowed
#
