# Warning: configuration file generated by SysDen64.
# To update this file:
#   - edit source: $HOME/sd64/etc/shared/MODULE/
#   - apply updates: sysden64 -u -m MODULE
# Version: 1.0.0

#
# Custom aliases definition
#
# * Use to add custom command aliases to the shell
# * Use standard born shell syntax to keep it portable between Bash, ZSH and SH
#

# Replace the placeholders remove the # to enable it
# alias X_COMMAND_ALIAS_X='X_COMMAND_X'
